sudo: required
dist: jammy
services:
  - docker

before_install:
  - docker build -t medali/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true medali/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "MyDockerApp"
  env: "MyDockerApp-env"
  bucket_name: "elasticbeanstalk-eu-north-1-586794465001"
  bucket_path: "MyDockerApp"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
